### ISSUE TITLE
No Space left on device when 

### ISSUE THREAD

**Issue by glovvorn** [CodeAndCoffeeBlog/building-ue4-dedicated-server-blog-1#1]
I'm running into an error in the Packer step when trying to create the AMI:

==> amazon-ebs: Error processing tar file(exit status 1): write /Linux/HavenServer.debug: no space left on device

I named my project 'Haven', so that file path is correct.  That debug file is ~1.5gig for reference.  I couldn't figure out how the EBS volume that's attached to this instance gets created.  How do I go about changing this so that it will build?

**Comment by neill** [comment]
+1 @glovvorn @lukebrady were you able to solve this?

**Comment by neill** [comment]
@glovvorn Sorry for the double ping- but just in case you still needed an answer here, or for anyone who comes across this- adding the below after `secret_key` in `docker_instance.json` will resolve this:
```
            "launch_block_device_mappings": [{
                "device_name": "/dev/xvda",
                "volume_size": 25,
                "delete_on_termination": true
            }]
```

What that does is sets your root ebs drive to spin up with 25gb of available space, as opposed to the 8gb that the source AMI specifies. 25gb is probably overkill so you can tune that as necessary.

**Comment by CodeAndCoffeeBlog** [comment]
@neill thanks for the PR. The base volume size will be 15 GB. Closing this issue.
